### ISSUE TITLE
JacobDanger's Final Project Proposal

### ISSUE THREAD

**Issue by JacobDanger** [cop1000/final-project#1]
### Proposed Project Description
I thought of making a mobile friendly tip calculator. A website that scales to fit phone screens that you could use to figure out your tip, or get a collective tip if the party is greater than one. I imagine the overall design to be minimalist, but not "cheap looking", so a lot of bootstrap and CSS. I want the website to also be able to show the total cost of a meal by adding in tax along with the desired tip. So the website will have a big field for someone to enter in the cost of their meal along with several check boxes to factor in tax and some predetermined tip percentages (12%, 15%, 17%, 20% ...), as well as a second field to enter in a custom tip (like 934%). As a final note, and more just for fun, I would like to add small pop up windows before you can see your total cost, which would display unsolicited (and sarcastic) life advice. 

### Connecting Concepts
This'll take a little bit of HTML, a lot a bit of CSS and jQuery, and a sprinkle of javascript. I don't intend for it to be crazy with the functionality, more angled to looking nice.

### Timing
I don't have a good estimate for how long it will take, but here's my schedule.
1) Draft the basic HTML structure and jQuery to get the input/output of the website in order
2) Follow up with the javascript to write the functions to calculate tips and add it all together
3) Run some tests to make sure it's implemented correctly
4) Spend the remaining time applying the makeup and cosmetics.

### Asking for...
As I want to make this pretty but lack the practice to really fineness it, I'm looking for a partner in crime. Someone who feels confident in turning a website from the 90s into something that would have been socially acceptable in 2004. Reply to this or send me a message in gitter if you're interested. The interview process is pretty casual, don't forget your resume, maintain eye contact and you'll be fine.

As far as feedback, let me know if there's something you always think about while figuring out how much you want to tip that sounds kinda like "wow, I wish there was some mediocre college student out there who knows exactly how to cater to my immediate tip oriented needs."

**Comment by rbowser5** [comment]
That would be really useful! Especially on your phone so I wouldn't have to drive home and check there and then back to the restaurant haha. Fluid containers FTW!

**Comment by hectorsector** [comment]
> The interview process is pretty casual, don't forget your resume, maintain eye contact and you'll be fine.

😆 

@JacobDanger this seems like a great project and definitely 👍 from me to move forward. However, I want to offer a few tips:

1. Let's target the functionality that you'll KNOW you'll have ready for submission -- that way if you go above and beyond, great, but if you can't get to the extra stuff it won't hurt your grade. Therefore, I suggest you limit your initial functionality to just show predefined tips. You can then iterate if you hit that target and add functionality for custom tips, split with friends, etc.
1. In today's world, you don't have to be a designer to design purdy things. I'm a big fan of [Font Awesome](http://fontawesome.io/icons/), [Octicons](https://octicons.github.com). Other useful references might be button son [Bootstrap](https://v4-alpha.getbootstrap.com/components/buttons/) and  [jQuery](https://jqueryui.com/button/).
1. If you do get a partner, please clearly identify how you'll work together before you begin to code.

**Comment by hectorsector** [comment]
One more thing! Do a quick search and see if there's an existing project on GitHub or elsewhere that you can leverage. Perhaps some of the basic functionality already exists out there and you can make it better.

**Comment by GoogleFox** [comment]
@JacobDanger and I will be working on this brilliant idea together! 👍

**Comment by hectorsector** [comment]
@JacobDanger Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
