### ISSUE TITLE
jenny0325's Final Project Proposal

### ISSUE THREAD

**Issue by jenny0325** [cop1000/final-project#10]
### Name
Jenny Saint Pierre
### Proposed Project Description
I have no idea what I want to make, my mind is racing everywhere, but I think I'd like to create a portfolio for some images that I will create. I plan to make the website responsive, and the images will have some effects to them as the mouse move over them. The images will be the focal point, there will a button on the images where people can submit their requests for prices, and there will also be a contact page for people to request customs images. I am debating whether or not to make it functional since the images won't be that great and people probably won't want to purchase them.

### Connecting Concepts
This will allow me to practice html, css, and bootstrap and possibly javascript.

### Timing
Research: Look for ideas on portfolio. 
Photographs: Create some images. 
Code: put everything together using html, css, jQuery, or bootstrap and possibly javascript.
### Asking for...
Should I make a gallery or just one picture per pages, thus making a multiple page website and should I make it possible for people to actually try and request a purchase price for the images or just put for the purpose of this project?

**Comment by aalevane** [comment]
What do you mean by making it functional? You mean the user being able to actually send their request? I don't think that's required for the project. My website is going to have a contact page too and I don't plan on making it functional in that sense since I'll still be showing my understanding with the HTML, CSS, JavaScript, etc on the page. But @hectorsector will correct me if I'm wrong 😜 As for the images, you don't have to use your own if you don't feel confident about them. You can use [Unsplash](http://www.unsplash.com)—they have beautiful, high-resolution photos, they're free to use and you don't have to credit them on your website.

**Comment by jenny0325** [comment]
@aalevane Yes, that's exactly what I meant by making it functional, and thank you for the suggestions. It's funny because the minute I saw this project thing, I had it in mind that I wanted to do exactly what you stated in your proposal, but then I was like read some of these proposals and see what other people are doing and then I read yours and I was like dang now I gotta do something else.

**Comment by KaidyCEThomas** [comment]
I definitely think using a stock image site will be more helpful in achieving your goals without recreating the wheel so to speak. I'll be using Little Visuals and now Unsplash per @aalevane's suggestion for my food blog. Time-savers!!

**Comment by hectorsector** [comment]
@jenny0325 good suggestion. I would ask that you look into what sort of JavaScript you will practice in this project, if you're using a contact form, indicate exactly how that contact form will be submitted. If you're using a slideshow, find the JS that will power it. I want to ensure that you're getting the opportunity to practice and code something -- there should be at least a little bit of customization in your project. Say, for example, that you find a service that helps you submit contact forms, I want you to be able to customize it successfully to include the right destination for the contact information and such.

**Comment by jenny0325** [comment]
@hectorsector I don't get what you mean, I will be coding the site from scratch but the contact form will not be functional in the sense that people can actually send their requests; that would require PHP and I don't plan on using that.

**Comment by hectorsector** [comment]
@jenny0325 your site needs some JavaScript in order to count for credit. So my request is to identify what JavaScript you will use in your site.

**Comment by jenny0325** [comment]
@hectorsector What if I add a scrolling effect using javascript and jQuery, like parallax scrolling and a text typing effect? I honestly don't know, maybe you could suggest what you want me to use javascript for, that would be easier because right now I don't know what I want to use javascript for.

**Comment by jmasterson5** [comment]
it's a good idea all I will say is to think more about the specifics to what you want to have in that portfolio and how you plan on going forward with the idea

**Comment by hectorsector** [comment]
@jenny0325 the parallax effect is alright -- I don't want to influence your idea I just want to be sure it contains the elements required for full credit.

**Comment by jenny0325** [comment]
@hectorsector Ok thank you.

**Comment by hectorsector** [comment]
@jenny0325 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
