### ISSUE TITLE
Javier-of-the-Rich-Port's Final Project Proposal

### ISSUE THREAD

**Issue by Javier-of-the-Rich-Port** [cop1000/final-project#11]
### Name
Javier Barea

### Proposed Project Description
I would like to make a game of tic tac toe in javascript that can be played through the web-browser and scale as needed to be played on a phone as well. The game would just be the player against an A.I. and would keep track of wins and losses

### Connecting Concepts
It would use Javascipt as its core with css and html to display it

### Timing
I feel the project will take at least a week, as while the game would be simple, it will probably need alot of checks and loops internally that would need to be tested at each step. Simply making sure that the code could react to every combination of wins (when ever someone makes a row) could take a day itself.

### Asking for...
Any criticism or feedback you guys can think of

**Comment by aalevane** [comment]
Great idea! I can't think of anything that may be wrong with it. It's simple and it will show off your skills nicely. Good luck!

**Comment by marxspawn** [comment]
I am interested to see where you go with this. The counter action from the A.I. will be fun to develop. good luck with this, i will definitely check out the final run on this

**Comment by Jordan-Hosein** [comment]
As @marxspawn said, I'm interested in seeing the counter action from the A.I. 
Sounds fun and good luck!

**Comment by jenny0325** [comment]
@Javier-of-the-Rich-Port I think that's a great, and I can't wait to see how it turns out.

**Comment by lucianoh** [comment]
This is a great idea! Looking forward to trying it out when you finish.

**Comment by bbutner1** [comment]
I really like the idea of this since I did this in a high school class I took on Javascript. This is definitely doable and I think this is a great first step towards creating bigger and better games/apps that can be used by many people.

**Comment by hectorsector** [comment]
Great idea, @Javier-of-the-Rich-Port! I want you to please research some existing JS Tic Tac Toe projects and find out whether you can use an existing one and customize it to add some features, or whether you will create one from scratch. Once you've done that, I'm happy to approve.

**Comment by Javier-of-the-Rich-Port** [comment]
Most of the existing games seem to have the A.I. stick one difficultly level, I think I can use some of these and customize it so the A.I. becomes smarter or dumber based on the number of wins/loses.
Would this be acceptable?

**Comment by hectorsector** [comment]
Can you link me to some @Javier-of-the-Rich-Port?

**Comment by Javier-of-the-Rich-Port** [comment]
The main sources I used for this were javascript instruction book I had at home but online I found this http://jsfiddle.net/nishacodes/2Jvtu/ as an example. It always checks the players set up first. I figured I could make a check and a function that would scale the chance of it making a random move with player losses until it reach completely blind play

**Comment by hectorsector** [comment]
@Javier-of-the-Rich-Port So if I'm understanding correctly you want to take the code you linked and customize it so that there's a beginner, medium, and hard difficulty level?

**Comment by Javier-of-the-Rich-Port** [comment]
Sort of, thy way I was thinking of doing it was a sliding scale based on your wins and losses but I could do 3 difficulties as well if that would be a better project

**Comment by hectorsector** [comment]
@Javier-of-the-Rich-Port either of the two ideas is fine, I just wanted to be sure there would be a significant modification. It sounds like there is so please carry on 👍

**Comment by hectorsector** [comment]
@Javier-of-the-Rich-Port Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
