### ISSUE TITLE
Jomarm92x's Final Project Proposal

### ISSUE THREAD

**Issue by Jomarm92x** [cop1000/final-project#12]
### Name
Jomar Marquez.

### Proposed Project Description
For my final project I don't exactly know what to do as the possibilities are endless when it comes to programming so I thought maybe to go simple: a calculator. We have all seen and used one, but never done the math behind what does that same math FOR you. It is the reason I love math and have grown into programming as a later career choice. It shouldn't be too hard to make and maybe I could extend it further to a scientific calculator.

### Connecting Concepts
I would say that the concepts I would implement would consist of a bit of JQuery, JavaScript, HTML, and CSS. Since it is mostly math equations, JavaScript will be the main focus to this project.

### Timing
I have never timed myself on things like these because I tend to underestimate the work ahead of me but I would say that it should take me from this Thursday to the Thursday of the final project being due with maybe about 2 hours a day to get everything cleaned up and working (As I have 3 other finals to enjoy haha).

### Asking for...
If anyone has an idea of a feature I could add on the calculator that they always wanted and it never had, something a beginner programmer could do of course haha.

**Comment by JBrady22** [comment]
I think you have a good plan to get this done and i think you and me are on the same boat with having 3 other finals as well. A little side thing that always bugged me with a calculator was when you had a really hard function but you can only put in in Y=.......... form rather than Y+7/2=..... form. that would be really hard to code i am sure but i just wanted to ADD this in there. pun intended.

**Comment by mdean19** [comment]
I think it would be awesome to try and do this (: I'd like to see how you code it and all!

**Comment by jenny0325** [comment]
@Jomarm92x I agree with @JBrady22, so if it is possible for you to do it would be really great.

**Comment by ClicheUsername** [comment]
I think this can definitely be done in the time frame, but I'd say prepare yourself for some frustration, I've made a calculator before in another language and it sounds a lot easier than it is (then again, I'm not great with math in the first place). I'd love to see an integer to binary feature though, if you're up to it.

**Comment by hectorsector** [comment]
@Jomarm92x could you do a little research and see what JS Calculators already exist? Then, let's examine them and see if you can reuse one that exists and add functionality to it, or create one from scratch. Once we've looked them over I'll approve.

**Comment by Jomarm92x** [comment]
http://thecodeplayer.com/walkthrough/javascript-css3-calculator @hectorsector how is this? maybe I could add customized buttons for scientific calculator functions or for the suggestions given, or I could just go ridiculous and add bogus buttons that lead the user to a completely unrelated website just for fun? Possibilities are endless haha

**Comment by hectorsector** [comment]
@Jomarm92x go ahead and expand this one to be a scientific calculator. Approved!

**Comment by hectorsector** [comment]
@Jomarm92x 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
