### ISSUE TITLE
JBrady22's Final project proposals

### ISSUE THREAD

**Issue by JBrady22** [cop1000/final-project#13]
Name:
Justin Brady

Proposed Project Description:
My idea for this project is similar to @StephanNears. I came up with this idea two days ago and haven't been on since so it is very coincidental that this happened. Mine is different in the fact that mine will have 4 questions with 16 possible outcomes. the way you answer the questions will lead you to one of these outcomes. I am thinking doing to where depending on how you answer the questions it will tell you what type of gamer you are OR what type of video games you play. This will probably get changed but the overall concept is the same.

Connecting Concepts:
I will be using HTML, CSS, Bootstrap, and Javascript to complete this.

Timing:
This will take me probably until the due date or the day before to complete. I work during the days so i will have to be extra focus at night to complete this. I am going to be researching more into the topic of the quiz and get that concrete by Monday or Tuesday. Then i will work on the code until a few days before the due date. then i will be testing its functionality by making sure every one of those 16 options work. the i will be complete.

Asking for:
Advice or input to the quiz. i will even take quiz ideas because you may have a better one than mine but i would like to keep it gaming themed.  overall i look forward to implementing my skills that i have learned in this class.

**Comment by Jordan-Hosein** [comment]
Type of video games you play might be an easier test since you're going for 16 outcomes. However, that's just me because I can't think past about 5 different types of gamers. 
I look forward to taking the test! I'll probably get FPS or RPG if you do it on type of game.

**Comment by mdean19** [comment]
This sounds pretty cool, I'd like to know where I fall in the type of gamer I am.

**Comment by JBrady22** [comment]
I thought about it at work today and i am pretty sure there will be 20 possible outcomes since there are four questions. If i a m wrong on this math let me know. I originally thought like normal 4x4=16 but when i thought about it i forgot that marking the same letter for every answer is an option whereas 4x4 is if you choose a different answer each time.

**Comment by JBrady22** [comment]
Also i think i am changing my ideas to be more of which video game you should buy this Christmas season and i will put down some games that have come out and some games that are not out yet.

**Comment by ZPeterson2** [comment]
You should make it a text-based game. Where each answer leads you down a different path of the story and have multiple endings. So the game can change every time you play it. And maybe have more questions with less options to make it longer.

**Comment by hectorsector** [comment]
@JBrady22 great idea that I'm happy to approve. My suggestion is to brainstorm out the possibilities now before you start coding. The content is just as important as the coding behind it.

**Comment by hectorsector** [comment]
@JBrady22 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
