### ISSUE TITLE
AGuerraDumas' Final Project Proposal

### ISSUE THREAD

**Issue by AGuerraDumas** [cop1000/final-project#14]
Name
Andyel Guerra Dumas

Proposed Project Description
I plan to build a website that gathers hobbies and the necessary materials to start the hobbies. I'll also add images and link them to website pertaining to the hobby. To make the website I'll use Html and CSS. I'll also add a calculator to add up the average total for the startup cost of the hobbies, if necessary. For this I'll use some basic JavaScript.

Connecting Concepts
I will need to use Html, CSS, and possibly a little JavaScript.

Timing
First, I would need to build the frame for the website, this could take till 12/7/2016. Then I would need to add in the hobbies, and make a simple calculator to help determine the average initial price for the hobby, this could last maybe till 12/12/2016.

Asking for...
Some hobbies that they enjoy, and materials that are necessary for initial startup.

**Comment by ClicheUsername** [comment]
This sounds like a great idea, for the calculator, are you planning on using say, a list with tickboxes and once they have checked all of the boxes, a button labeled "Total" or something of that sort, that will add everything up? If not, I would say that might be a good route to go for this. Can't wait to see how it turns out.

**Comment by kzeng16** [comment]
How many hobbies do you plan on starting with?

**Comment by hectorsector** [comment]
Hi @AGuerraDumas -- this project seems like a good start, but a little too open ended. Can you give me some examples of how the hobbies would map out to starting costs, and how many hobbies you support? Perhaps outline a path that a typical user would follow when they enter your web site? That'll help us find the right way to adjust your project.

**Comment by AGuerraDumas** [comment]
@hectorsector I am thinking of doing around ten hobbies, the path would be similar to the my first website project that we had, I was originally thinking of giving the price of each item, then having a calculator on the website so users wouldn't need to open the calculator app, but I am interested in @ClicheUsername 's idea, and may try it if I feel like I have the capacity to do it.

**Comment by hectorsector** [comment]
Thanks for getting back to me, @AGuerraDumas. I would need to see what the hobbies are and the exact path users would follow in order to approve the idea.

**Comment by AGuerraDumas** [comment]
Hobbies I currently have thought of using: Blacksmithing, Woodworking, gaming, Paintball, Airsoft, Painting, Photography, Martial Arts, Book Collecting, and Fishing. For the path: Everything will be on one webpage, there will be a directory at the top with a list of the hobbies with links to get to each section.

**Comment by cristivela1217** [comment]
How many hobbies are planning on having?

**Comment by AGuerraDumas** [comment]
@cristivela1217 I have 10 hobbies on it right now.

**Comment by hectorsector** [comment]
@AGuerraDumas since the project is due tonight, please submit what you've got and I can grade it from there.

**Comment by hectorsector** [comment]
@AGuerraDumas Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
