### ISSUE TITLE
KaidyCEThomas Final Project

### ISSUE THREAD

**Issue by KaidyCEThomas** [cop1000/final-project#15]
### Name
Kaidy-Ann Ellis-Thomas

### Proposed Project Description
For my final project, my thought is to create my first food blog; I think it would be great to kind of capture the essence of these meals as I create them through images of food art and recipe sharing. I'm definitely a foodie, whether it's re-creating spice-filled meals from my Jamaican background or trying a new "meat-less" or vegan recipes I'm on board!!

I'll gut the first project we did which will allow me to use the bones of my HTML and CSS code to format the blog. I'll also use a bootstrap blog template. Most importantly I will show some Java skills by creating a few call-to-action slides or pop ups.

### Connecting Concepts

1. HTML/CSS 
2. Bootstrap 
3. JavaScript
4. CodePen

### Timing
Since I have a little bit of the work already (HTML/CSS), I'll spend most of my time with the Java portion of the project. Not sure if I'll have enough time since I've never really created anything this extensive.

### Asking for...
Thoughts on timeline; feedback on overall scope of project and topic

**Comment by jenny0325** [comment]
@KaidyCEThomas I would personally love to read it when it is finished. As for the timeline I think it's going to take a little while to come up with the contents, but since it's a blog you can post the content whenever, so it will be fine.

**Comment by mirenagreen** [comment]
@KaidyCEThomas I liked that your project is simple but contains the main topics we have learned throughout this semester. For the time frame, I think you have enough time. And maybe you could put some interesting story about the food or what kind of occasion the food would be good for, etc. Good luck on your project!

**Comment by hectorsector** [comment]
@KaidyCEThomas sounds like a great idea! There's no shortage of blogging templates out there that I do hope you will use. My one request is that you identify one JavaScript item you'll add, it sounds like you're going to use callouts for images which is fine with me, just make sure that part is prevalent as coding in JS is a big chunk of your grade. Happy coding!

**Comment by hectorsector** [comment]
@KaidyCEThomas Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
