### ISSUE TITLE
Jordan Hosein's Final Project Proposal

### ISSUE THREAD

**Issue by Jordan-Hosein** [cop1000/final-project#16]
### Name
Jordan Hosein

### Proposed Project Description
I would like to create a website on possible habitable exoplanets. I've been interested in space since I was five years old and will be going to college to major in Astrophysics so making a website on a space subject will be very interesting and enjoyable for me. I plan to have information on the exoplanets, such as location, distance, elemental composition, mass, and other ~~nerdy~~ fun facts. I'm also thinking about making a little calculator on the side of each page that will show how long it would take to travel to the planet by the Space Shuttle Main Engines (SSME or RS-25) or the Space Launch System (SLS) which will be used for the Mars Mission (might just end up only letting SLS be the choice as the SSME is being redesigned for the SLS if used instead). 

### Connecting Concepts
HTML, CSS, jQuery, Javascript, and Bootstrap  

### Timing
Research the planets, get necessary information written down, do all the maths. **12/5 - 12/6**
Coding the website and making it look pretty and working. **12/6 - 12/10**
Get the calculator for each of the planets  **12/11-12/13**
Any final ~~panicking~~ fixing and trouble shooting **12/13-12/14**

### Asking for...
Any feedback or comments.
Maybe a partner if they're interested in this kind of stuff 😁 
Checking my math to make sure it's correct 😖

**Comment by lucianoh** [comment]
Looks like you're on the right track. You have an interesting concept and you know what you're going to do and when you'll do it as well. Good luck!

**Comment by MCastro46** [comment]
Ah, Astrophysics, my long lost love, alas, we are like star crosses lovers at the moment.
I can't wait to see what you come up with! do you have any criteria,  you looking into? i.e What planets are you currently looking into? Why?  are you looking at just a few of them for now?  Keep me updated! im 100% interested in this!

**Comment by Jordan-Hosein** [comment]
Haha!
Top possibly habitable planets from NASA, I so far have some info on 6 planets, I'll add more if I have time. 
Wolf 1061c
Kepler 442b (I'm actually related to Johannes Kepler :P) 
Kepler 186f
GJ 667Cc
Kepler 62f
Kepler 438b

**Comment by hectorsector** [comment]
@Jordan-Hosein I love astronomy-related things, they make me happy! I like the idea of the calculator and would suggest you make that your entire project. If you want to build on it later and add a database of planets that's doable, but let's stick to one thing for your project. Does that sound OK to you? If so, I'm happy to approve this.

**Comment by Jordan-Hosein** [comment]
@hectorsector
Ok! I'll still probably include just a couple facts about each planet then, but not an entire page of info.

**Comment by hectorsector** [comment]
Great! Carry on then.

**Comment by hectorsector** [comment]
@Jordan-Hosein 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
