### ISSUE TITLE
Mariadodoll: Final Project Proposal

### ISSUE THREAD

**Issue by mariadodoll** [cop1000/final-project#17]
### Name
Maria Dodoll

### Proposed Project Description
For my final project, I would like to create a herbalism blog featuring various plants. My blog will have information on various plants their origins of the plants and medicinal properties. I will also provide information how these plants have been the basis for medical treatments through much of human history. Also I will provide information on how such traditional medicine is still widely used today.

### Connecting Concepts
I will utilize the following programming languages that I have learned in this class;

1.	HTML/CSS
2.     Java Script
3.	Bootstrap
4.	CSS

### Timing
I believe this project will take me 5 days to complete. I will start off by researching and gathering information on the various plants. I will then collect pictures of the various plants. After I have collected the pictures I will start to develop and put my blog together with all the information I have gathered.

### Asking for...
Thoughts and feedback on the coding language that I should use and the overall scope of my project and topic.

**Comment by jenny0325** [comment]
@mariadodoll I like that idea, and I think you could use html, css, and bootstrap to make it responsive.

**Comment by Jordan-Hosein** [comment]
I second @jenny0325 
Sounds interesting!

**Comment by mirenagreen** [comment]
@mariadodoll your project will have a lot of interesting information to read! Maybe you can make a use of the lessons we have learned by putting the information in organized pages such as by symptoms, or place of origin, medical purposes, etc. Just an idea! Good luck!

**Comment by hectorsector** [comment]
@mariadodoll I'd like to know a little more about how you'll use JavaScript in your project. Can you identify one distinct thing you'll do in JS and we can move forward from there?

**Comment by cristivela1217** [comment]
I really like the idea of making a blog format

**Comment by mariadodoll** [comment]
I decided not to use Java Script in my blog. I was going to create a widget using javascript that would have been displayed on my blog. https://mariadodoll.github.io/Herbalogic/

**Comment by hectorsector** [comment]
@mariadodoll since the project is due tonight, please submit what you've got and I can grade it from there.

**Comment by hectorsector** [comment]
@mariadodoll also please make sure you submit via Pull Requests as described in the instructions.

**Comment by mariadodoll** [comment]
@hectorsector I tried to submit the final project as a Pull Request on my github account but it did not work. I will try again.

**Comment by mariadodoll** [comment]
I utilized java script widgets to change the language of the information on my page and also to share and print my page.

**Comment by hectorsector** [comment]
@mariadodoll Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
