### ISSUE TITLE
mdean19's Final Project Proposal

### ISSUE THREAD

**Issue by mdean19** [cop1000/final-project#18]
### Name
Michael Dean

### Proposed Project Description
For my final I thought I would create a blog about video games. I would like it to have my reviews on recently released video games, while also providing information on them. The games would also have trailers and/or screenshots accompanying them. I've played pretty much all of the recent big hits so I think this would be great for me. I would like to make it very user friendly to get to each game's review/info too. And if possible, separate by platform or genre.

### Connecting Concepts
HTML
CSS
Bootstrap

### Timing
It shouldn't take me too long.. already had the practice with the website we made a few weeks back.

### Asking for...
How to make everything look neater and have things correctly link to each other.

**Comment by lucianoh** [comment]
I can't wait to see how this turns out!

**Comment by KaidyCEThomas** [comment]
This sounds so cool; excited to see what games you cover! Just a note that @hectorsector will probably ask to see some JavaScript or jQuery so you can show off your awesome skills with those particular languages. Good luck to you!!

**Comment by MCastro46** [comment]
@mdean19  This sounds like a great start! are you sticking to just one genre of gaming, or a mixture of them all?

**Comment by mdean19** [comment]
@MCastro46 I'll probably stick to FPS and Action Adventure games, and maybe FFXV as the sole RPG aha.

**Comment by hectorsector** [comment]
@mdean19 I'd like to know a little more about which JavaScript components you'll be adding to your blog. Can you explore that a bit and let me know?

**Comment by hectorsector** [comment]
@mdean19 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
