### ISSUE TITLE
lucianoh's Final Project Proposal

### ISSUE THREAD

**Issue by lucianoh** [cop1000/final-project#19]
Luciano Harris

### Proposed Project Description
I am thinking about creating a website based off the Final Fantasy game series. Seeing as how the 15th game in the main series was just released I figured it would be something fun to do. My website will contain information regarding the history of the series, plot summaries of the most popular entries, and info on some of the main protagonists. These are only a few ideas I have and I will more than likely add to this list.  

### Connecting Concepts
I am expecting to use HTML, CSS, Bootstrap, and JavaScript.

### Timing
12/5 - Research topic
12/6 - Begin coding site
12/7 - Add info/pictures/etc
12/8 - Finalize everything

### Asking for...
Any feedback or suggestions anyone may have to improve the quality of my work.

**Comment by lminks** [comment]
You and @MCastro46 both with Final Fantasy! Maybe you two could bounce ideas off of each other or come up with topics to use. Summarizing the lore of the games sounds like a good idea, since I often find it difficult with a lot of series to find anything about their lore without it being entangled with a lot of other extraneous information. Considering the size of the series at this point, you probably have a more than adequate amount of material to work with.

**Comment by ZPeterson2** [comment]
This is a good start for the final project. The only thing I would add is something to make the website more interactive, like a comment section or quizzes.

**Comment by kzeng16** [comment]
This is interesting, as someone who is interested in playing the games, will your website contain a lot of spoilers?

**Comment by hectorsector** [comment]
@lucianoh good start, but I'd like to know in particular what would make your web site use JavaScript. I see some good suggestions from @ZPeterson2 ☝️

**Comment by lucianoh** [comment]
@kzeng16 I will make sure that my site is spoiler free.

**Comment by lucianoh** [comment]
@hectorsector  I'll use @ZPeterson2 suggestion and add a comment section.

**Comment by lucianoh** [comment]
Thanks for the responses everyone!

**Comment by hectorsector** [comment]
How will you use the comment section, @lucianoh?

**Comment by lucianoh** [comment]
It will be my way of answering any questions anyone may have regarding the story, characters, or anything related to series.

**Comment by hectorsector** [comment]
Alright, please go ahead and start implementing.

**Comment by Mikedaris94** [comment]
I can't wait to see your project it looks like a good idea. I use to be a final fantasy fan but I kind of lost track of the games so i hope you do well and good luck!

**Comment by hectorsector** [comment]
@lucianoh Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
