### ISSUE TITLE
Julian Masterson Final project

### ISSUE THREAD

**Issue by jmasterson5** [cop1000/final-project#2]
Julian Masterson

### Proposed Project Description
I plan on creating a walk through guide for a video game called Xenoblade chronicles X. This webpage will include pictures of game play through out the guide helping to give a visual view of the game. The web page will also include links to other pages that include info specifically to certain things like battle class's and districts. Another thing the web page will include is video of the game giving more visual content to the viewers. The site will also use bootstrap to allow the website to be viewed on the go making it easier for gamer's to get the info they need on the go. last there will be links to stores where the viewers may buy the game if they don't already own it.

### Connecting Concepts
The biggest topic this project will give me practice is Html due to me creating a web page but it will also include bootstrap to make the site adapt in size depending on whether your using a phone or a computer to view the website. Last it will use Css to help give design to the site like pictures and color through out the site.

### Timing
It will probably take about a week to complete this project maybe longer but as long as I take the time and effort to create this web site I should be able to make it by the due date.
I plan to get the layout done on December 1
the code done between December 3-5
then last I will finish the editing between December 5- the due date

### Asking for...
nothing really but If I do need help I will email the teacher

**Comment by rbowser5** [comment]
That's a really good idea, love me some Xenoblade. I'd definitely recommend creating a glossary at the beginning to auto-scroll to the correct part of the guide, or maybe have each chapter of the game split into different parts of the site.

**Comment by hectorsector** [comment]
@jmasterson5 great idea! One suggestion I might make is to think about how you could incorporate a little more JavaScript to show off your programming chops. 

![](http://i.giphy.com/TjUytMXiJ8CT6.gif)

Some ideas (any one of these would work, or something altogether different):
- Add a feature where you show the visitor a GIF from a list of your favorite video game GIFs (something like the [Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine) but with GIFs instead).
- Display a banner that tells your visitors when you're live streaming your gameplay and when you're offline (like the [Twitch.tv API project on FCC](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api).
- Build-in a questionnaire that asks the visitor a few questions and then appropriately directs them to buy the game or jump right into the walk-through, etc.

Once you find the JavaScript that you'd like to add, I can help you scale back the amount of content so you don't have to be crunched for time. I look forward to this! Let me know how you want to move forward.

**Comment by hectorsector** [comment]
@jmasterson5 have you had a chance to see this feedback?

**Comment by jmasterson5** [comment]
So I think I will include a questionnaire as my way of including java script in my website to see the sites viewers interest to see if buying xenoblade chronicles x is worth buying or if you click already owned direct you strait to the walkthrough

**Comment by hectorsector** [comment]
Alright, carry on then!

**Comment by hectorsector** [comment]
@jmasterson5 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
