### ISSUE TITLE
Lolivo's Final Project

### ISSUE THREAD

**Issue by Lolivo** [cop1000/final-project#20]
### Name
Luis Romero-Olivo

### Proposed Project Description
I'd like to make a website that contains my favorite memes that have spawned throughout time. Also a little bit of information about their background, such as they time they came about, their meaning and the place or work of media where they came from.I want to include gifs as much as pictures. I want the website to be organized neatly and very humorously presented.
### Connecting Concepts
HTML ,CSS, Bootstrap and a little javascript to make a randomized meme selector from the list.

### Timing
It will take around a week to complete. From the initial procurement of curated memes, which will be obtained from archives that preserve memes from 4chan, reddit and Facebook amongs other taiwanese imageboards.To the research of their ancient origins most likely from Knowyourmeme.com which would take around a day. the rest of time time would be spent with the design and development of the website, the careful and skillful placing of the collection of curated memes.
### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?
Mostly design feedback, such as good or bad website design choices on my part and ways to improve on them

**Comment by radicalpharaoh** [comment]
Quite informational regarding the source of memes. Sounds like an interesting project to both be a part of and have a challenge at. You pretty much went over what's needed to be covered. Any issues you might think you run into? If not, then good luck, man!

**Comment by hectorsector** [comment]
Fun, unique projects @Lolivo! How are you going to get that data? Are you going to create it yourself or rely on some internet database of memes that has origins and such? Also, what sort of JS element will you add to bring in some of what you've learned this semester?

**Comment by Lolivo** [comment]
@hectorsector Done, it's been corrected!

**Comment by hectorsector** [comment]
I'm not sure I understand, @Lolivo. Could you answer the questions I asked, please?

**Comment by Lolivo** [comment]
Oh, I'm really sorry @hectorsector I just thought I'd have to update the description, as for the memes themselves they can be found floating in different archives depending on where they originated. After I find these memes, The information behind them can most certainly be found on knowyourmeme.com,  I will summarize this information while also adding a bit of my own memories/experience with the meme. The way I want to design the page and organize it is in the form of a gallery. As for the JS element, I want to use the random number operator and use it to make a button which zooms you into a random meme inside the page.

**Comment by hectorsector** [comment]
Apologies, @Lolivo. I didn't realize you'd updated the OP. How are you doing on timing considering this is due tomorrow?

**Comment by Lolivo** [comment]
@hectorsector Good good I have all my memes picked out and now I'm just figuring the layout and everything else, it should be on time!

**Comment by hectorsector** [comment]
@Lolivo 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
