### ISSUE TITLE
MCastro46's Final Project Proposal

### ISSUE THREAD

**Issue by MCastro46** [cop1000/final-project#21]
**Please change the Title of this issue to include your username, something like: hectorsector's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Magdiel Castro
### Proposed Project Description
Create a both browser and mobile friendly webpage, that will act as a guide for newer players on Final Fantasy XIV, as well, as feature a way to post comments/questions. and a way to reply to them.

### Connecting Concepts
I will be using several concepts learned in class, Including, Bootstrap, CSS,  HTML, and a  Chocobo Dash of Javascript!
### Timing
12/5- Sketch and plan the layout/ color scheme
12/6-12/08- do in game "Research"...**
12/08-12/08.5  Cry and realize i haven't done anything but game.**
12/08-13 Code the webpage.
12/14- Final look over and submission

*ALL TIMING SUBJECT TO CHANGE WITH OUT-NOTICE

### Asking for...
Any sort of feedback, to help improve the quality of work provided, as well as any aesthetic improvements.

**Comment by lminks** [comment]
A walkthrough guide sounds like a good idea to me. Depending on how you approach it, the text itself describing the various aspects of the game could potentially require the largest share of time spent on the project, so I'd keep that in mind when planning your layout and time schedule.

**Comment by hectorsector** [comment]
@MCastro46 fun stuff! The comment part is necessary for credit as it will use JavaScript. Can't wait to see it!

**Comment by hectorsector** [comment]
@MCastro46 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
