### ISSUE TITLE
jriosrodriguez's Final Project Proposal

### ISSUE THREAD

**Issue by jriosrodriguez** [cop1000/final-project#22]
**Name**
Joel Rios

**Proposed Project Description**
We are planning on building a website. It will incorporate details about MIT; one of the most prestigious and elite schools. In tabs it will include location, GPA, and test scores required for the schools. Furthermore, images of the schools will be added (logo, campus, etc.)

**Connecting Concepts**
What lessons/topics will this project allow you to practice? A good final project will cover at least 2 big picture topics from class.
-HTML5 and CSS
-Web basics

**Timing**
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates.
Day 1 - Research 
Day 2 - Design
Day 3 - Code (text, titles, etc.)
Day 4 - Code (text, titles, etc.)
Day 5 - Code (images, web template)

**Asking for...**
What kind of feedback can your classmates and professor provide to help you be successful?
Suggestions of things that could be added to the website.

**Comment by radicalpharaoh** [comment]
Project sounds simple but useful for college students looking at what it takes to get "there". Could you guys elaborate on who is doing what for the project? Who's in charge of the Javascript and who's in change of HTML? Or how are you guys going to split up the work? Also, elaboration on the Timing section would be amazing just so everyone can understand how you're gonna address each part of the project. Other than that, this project sounds nice and simple!

**Comment by hectorsector** [comment]
@jriosrodriguez this seems like a pretty big project to tackle. Can you narrow it down to one thing you can do to practice what you've done this semester, and call out specifically what sort of JS you can implement? 

@cristivela1217 I need you to comment here so I can give you credit when I grade this.

**Comment by jriosrodriguez** [comment]
To be clearer, the website will be like a blog (to practice my HTML and CSS skills that I've learned this semester), where, specifically, this entry will be about some of the top Ivy League Schools (ex: Harvard, MIT, Stanford), their acceptance rate, average SAT scores, background history, a fun fact, etc. JavaScript will be used for any slides or to add details into the content within HTML (such as to change text or titles).

P.S. @cristivela1217 and I (@jriosrodriguez) won't be collaborating on this project.

**Comment by hectorsector** [comment]
@jriosrodriguez instead of an entire site about colleges, just a small page about MIT and their acceptance rate? I still don't understand how you'll use JavaScript -- what do you mean for slides? Are you including some sort of slide presentation with animation?

**Comment by jriosrodriguez** [comment]
@hectorsector No problem! Regarding JavaScript, I was planning on having the page with random numbers, perhaps numbers that look like binary, and once you click a button, it will transform those numbers into actual text; therefore, it would be interactive.

**Comment by hectorsector** [comment]
Thanks for the update, @jriosrodriguez. Since the project is due tonight please turn in what you've got and I'll take it from there.

**Comment by hectorsector** [comment]
@jriosrodriguez 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
