### ISSUE TITLE
kzeng16's Final Project Proposal

### ISSUE THREAD

**Issue by kzeng16** [cop1000/final-project#23]
kzeng16's Final Project Proposal

### Name
Keanu Zeng

### Proposed Project Description
I would like to try to create a random Pokemon team generator. It will generate a team of six pokemon. I think including all 700+ pokemon would be too much for me, so I will only include the new Alolan pokemon and region variants. The generator will be on a website and may include the sprites for each pokemon. The website will be a simple design.

### Connecting Concepts
HTML, Javascript, Boostrap, and CSS

### Timing
The project probably take around a week. I will put a few hours into it a day.

### Asking for...
Feedback on how I can make this work and if it's possible to do in time.

**Comment by ClicheUsername** [comment]
I think this is definitely possible to do in the time frame given. I actually made something recently to teach myself more about arrays, and multi-dimensional arrays, and I needed a ton of "usernames". I was able to find a huge text list of random usernames that I ended up using. Search around and see if you could find someone who has made the same for all the pokemon. The choice is yours but I think it would be neat if you could get them all in there. 

I was able to find a Google Doc on a reddit post that someone made containing them all, if you're up to it, maybe you could find a way to pull all the names from there? Just a thought. :)

https://www.reddit.com/r/pokemon/comments/1qrnw8/i_made_a_few_plain_text_printer_friendly_pokemon/

**Comment by ZPeterson2** [comment]
This is a great idea. I think cutting the amount of pokemon you include is a good idea. I think you should be a little more specific with your planned timing to make sure you finish on time.

**Comment by kzeng16** [comment]
Thanks for the feedback, I'll see what I can do with that list and hopefully add all of them in the generator.

**Comment by hectorsector** [comment]
@kzeng16 what a fun idea! Please just make sure that one of these projects doesn't already exist out there on the internet. If it does, please decide whether you'll use that and expand on it, or whether you'll create your own from scratch. Once you've got that, I'm happy to approve.

**Comment by kzeng16** [comment]
I am creating my own from scratch.

**Comment by hectorsector** [comment]
@kzeng16 alright, that sounds alright but please make sure you give credit if you do end up reusing any existing code.

**Comment by jjyates4** [comment]
This is a brilliant idea as it's my favorite game, will there be a possibility of a shiny pokemon being generated?

**Comment by hectorsector** [comment]
@kzeng16 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
