### ISSUE TITLE
ClicheUsername's Final Project Proposal

### ISSUE THREAD

**Issue by ClicheUsername** [cop1000/final-project#24]
### Name
James Pryde

### Proposed Project Description
Create a live updating weather app/webpage showing current weather in Orlando, FL. At this time I'm also considering making it into a Google Chrome plugin that will open as either the start page, or new tab page, and/or possibly having an icon in the top right.
(As shown below)
![Chrome Plugins](http://i.imgur.com/J5XRPMQ.jpg)

It would give easy access to current weather information, and I plan to add the option to change the city, etc. As well as allowing you to get more information than just weather right now, it would also enable you to get a 5-day forecast, as well as historical weather data, all of which could be available in the temperature (either Celsius, or Fahrenheit) of your choosing. 
**(Edit: I just remembered Chrome has built-in location if you allow it, so I may integrate that as well so you don't have to go in and change your location constantly, but that will be time permitting.)**

### Connecting Concepts
This project will allow me to practice integration with APIs, in this case, OpenWeatherMap.org's API, and making a page/app look good, and feel nice and responsive during use. I know that APIs weren't exactly covered during this course, but they are brought up in FreeCodeCamp once you get further into things, and I see it as an invaluable asset if I continue working on Web Development. I think that focusing on making it look and feel good is something that I can work on because personally I don't see myself as a creative person, I'm good at making things function, but not making them look good. I want to try to better myself in that area.

### Timing
I believe I can finish this within the time frame of the project, possibly sooner. By Wednesday, 12/7 I would like to have working current data from the OWM API. By Saturday, 12/10 I would like to have all API integration taken care of, including (and not limited to) getting data from other cities, 5-day forecast, and historical data for the chosen city. I would like to spend the rest of the time after that polishing the project, doing things like: Fixing bugs, testing on multiple devices, making it as intuitive & beautiful as possible, and (given enough time) turning it in to a Google Chrome app as I stated earlier.

### Asking for...
Any sort of feedback as to what I should (or should not) add to this. I don't expect everyone (or anyone for that matter) to use this aside from myself, but if you were going to use it, what would you see as being an important part of this? Was there anything I mentioned in my post that seems pointless to you? or anything that stood out that I should spend extra time on to make sure it is perfect? 

Also, if you would like to use this when I'm done, please let me know. I'd love to see some people using something I've made for once.

Thanks!

**Comment by lminks** [comment]
This seems like a pretty ambitious plan considering the material that was covered in the course, but it seems like an interesting one. As long as you haven't bitten off more than you can chew, I think your project is fine. I'd take it slow and only gradually add more functionality to it if you're comfortable with how it's turned out up to that point. All of your suggested possibilities seem like they cover all the information most people would want, so I wouldn't stress about trying to come up with more ideas.

**Comment by vcomney** [comment]
That sounds like a fun idea. If you think that the time table is doable, then I say go for it. I always like to see the radar of the current weather. I like having the advanced notice for worse weather coming when we are in a storm. Not sure how feasible something like that is to include.

**Comment by bbutner1** [comment]
I think this is a great idea and I would totally use it when it is done. I really look forward to being able to change the city as I do not live in Orlando but I would love to see features such as a 5-day forecast as well but that might be a bit much for a project, but if you know its something that you can do, then go for it man!

**Comment by radicalpharaoh** [comment]
This sounds like both something interesting to pursue and also very handy. Pretty nice idea you got there. Would love to see it fully functional and working. Wouldn't mind having it as a plug-in for my browser.

**Comment by ClicheUsername** [comment]
I appreciate all the feedback everyone, I'm very confident in my abilities to get this done in time.
I have already started working on this (here's hoping that @hectorsector approves it 😉) and I'm quite happy with what I have so far.

**Comment by hectorsector** [comment]
@ClicheUsername are you hoping to build upon the [Local Weather Project in FCC](https://www.freecodecamp.com/challenges/show-the-local-weather)? If so, I just want you to narrow down the scope a bit. A Chrome extension would be fantastic, but for now I would focus on just a web page, you can always scale up to an extension later. 

Let me know how it's similar or different to the FCC project and I'll be happy to approve.

**Comment by ClicheUsername** [comment]
@hectorsector I definitely see the similarities in my project to Local Weather. The main thing I'm going to be focusing on is getting a web page working with all the functionality I want, the Chrome extension will really just be something I'll try to convert it to if I have enough time. It's similar in the way that I have a header which is displaying the location, displays current type of weather, as well as an icon for it. I am also using the OpenWeatherMap API for my project.

Differences would be that I'm allowing users to type in a location that they want to see the weather of as well, not limiting to just where they currently are. I also have a 5-day forecast built in for highs and lows, and I should be able to add in expected weather (Rain, cloudy, clear, etc.). I'd also like to implement a history feature where you could go back and look at say the last week or so of weather.

**Comment by hectorsector** [comment]
👍 looks great, carry on!

**Comment by Mikedaris94** [comment]
This looks like it will be very helpful the those who are online 24/7 cant wait to see your project!

**Comment by hectorsector** [comment]
@ClicheUsername Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
