### ISSUE TITLE
Scoping.Vern.Comney

### ISSUE THREAD

**Issue by vcomney** [cop1000/final-project#25]
**Please change the Title of this issue to include your username, something like: hectorsector's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
What's your real name? Enter your first and last name in place of this text, please.

### Proposed Project Description
Give a detailed description of what you'd like to do for your final project (5+ sentences). Feel free to replace this text with your description.

### Connecting Concepts
What lessons/topics will this project allow you to practice? A good final project will cover at least 2 big picture topics from class.

### Timing
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates.

### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?

**Comment by ClicheUsername** [comment]
@vcomney Looks like you opened the issue but didn't fill out the info in it yet, just FYI in case it was an accident.
