### ISSUE TITLE
Final Project Proposal for VComney

### ISSUE THREAD

**Issue by vcomney** [cop1000/final-project#26]
### Real Name
Vern Comney

### Proposed Project Description
I'd like to do a web page that highlights my love of music. Basically, it will be a general and somewhat detailed (depending on time frame) digital exhibition of my influences and personal work. I have been writing, performing, and going to shows for more than 20 twenty years. Each moment shaping my approach and teaching me something. I will try to narrow the field by showcasing some of my favorite moments and pieces with this project. 

### Connecting Concepts
I really enjoyed the first portion of this class with regard to the html, jquery, and bootstrap coding that we did. I'm interested in exploring those aspects again with this project and maybe trying to throw a couple other tricks in there as well.

### Timing
I'm certain that most of my free time through out the week will be occupied by this. I'm going to start by first looking through my personal archives and then, narrowing the field of specific things to share. Once I have the materials settled upon I will string them together in a a manner that makes sense with regard to the flow of the page. I'm usually able to do this sort of thing quickly. Next I will begin the process of making the web page come to life and mimic the vision I have laid out on paper and in my head. There will be improvised tweaked along the way. i generally create in this way and I have a difficult time stepping outside of that and feeling comfortable with the end result.

### Asking for...
I think my biggest concern with this project will be the process of consolidating information into an aesthetic that flows while remaining comprehensive to the viewer. I think that feedback (positive or negative) regarding this will be helpful in me producing a finished project that I can be excited about. Also, any other general feedback is welcomed. I understand that the nature of this project will make it easier on both of us to have an open door policy when it comes to this stuff.

**Comment by hectorsector** [comment]
@vcomney I ❤️ when people have the opportunity to bring together what they've done in class with something they love. Would it be fair to say this is like a music portfolio? I think it's a great idea, I'd just identify one key element that you'll use JS for and make that the centerpiece of your project. Once we've got that identified, I'm happy to 👍

**Comment by vcomney** [comment]
@hectorsector Do you have any suggestions that would reflect what you are looking for from this project? I know we are supposed to come up with the idea on our own. I think that in my mind I am having an issue with sorting out a way that would play into my original concept as I see it and also offer up an appropriate amount of JS being used. It seems to me that I am just having an issue on creating something specific by marrying the two seamlessly. I may just be overthinking it. Either way, it is causing me to have a huge brain fart and there isn't time for that. I hope this makes sense. Any input or direction would be much appreciated. Thank you.

**Comment by vcomney** [comment]
@hectorsector I decided to add a generator in JS to the webpage where you can enter your name and it will return which one of my favorite bands you are. Hope this is acceptable. Please let me know asap, if it is not. Thank you.

**Comment by rthompson73** [comment]
@vcomney This sounds like a really cool project,  I am sure you will do a great job.

**Comment by hectorsector** [comment]
That's alright.

**Comment by hectorsector** [comment]
@vcomney Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
