### ISSUE TITLE
bbutner1's Final Project Proposal

### ISSUE THREAD

**Issue by bbutner1** [cop1000/final-project#27]
### Name
Brandon Butner

### Proposed Project Description
For my final project, I'd like to make a program that takes any string input and produces that string in binary code. For example the word Hi would be 01001000 01101001 in binary. I want to use Javascript for my program and then once i have the program working, make its own website that someone can use to enter their text and receive a binary output. I got this idea when reading Rbowser5's project proposal and figured I'd do something similar but different. Mine will just take any word/sentence and convert it to a binary code.

### Connecting Concepts
Javascript, HTML/CSS

### Timing
I feel like this project will take me a good bit of time since I have to write the code for 53 conversions being all the letters uppercase and lowercase and the [Space] character. I predict I will have the code done by 12/10 and have the website done by 12/13. 

### Asking for...
Any suggestions for my proposal in general would be nice.

**Comment by hectorsector** [comment]
@bbutner1 fun project! How will the translation happen? I'd start by figuring out that part first. It might interest you to know that each letter inside your computer is represented by a number, and each number can be converted to binary. For example, capital A is `65` in the decimal number system, and `01000001` in binary. There's no shortage of [ASCII tables](http://www.ascii-code.com) out there that you might want to look into.

**Comment by bbutner1** [comment]
Hi professor, I'm nearly done with my project, I just am having trouble with getting the 0's at the beginning. I tried messing with unshift but I dont know how to make it into an array to make it an 8 digit array... My code is at this link if you want to take a look https://jsfiddle.net/bbutner1/fo9tuz4d/

**Comment by hectorsector** [comment]
I don't think you have to worry too much about that, @bbutner1! I like it the way it is. I would just suggest adding some instructions for the user letting them know what your page does and how to use it.

**Comment by bbutner1** [comment]
@hectorsector I'm having trouble with the desktop app for the final project. I cant change any of the text on any of the files while trying to edit the devel. Also when I switch to my own compare branch, everything just disappears. Not sure what I'm doing wrong. Please let me know if you have any advice. Thanks

**Comment by bbutner1** [comment]
@hectorsector I also created a repository for the website for my project but its only showing the Header and I'm not sure why it isn't showing the rest. The link for my index.html is here https://github.com/bbutner1/final/blob/master/index.html

**Comment by bbutner1** [comment]
@hectorsector I got it to work!

**Comment by bbutner1** [comment]
@hectorsector I cant figure out how to create a pull request because it's not letting me choose a branch, maybe because I made a repository for it... I couldn't get the regular repository to work so I made my own repository and now I can't branch it but I have my completed Final project at this website https://bbutner1.github.io/ It has instructions on the site. If you know what I should do to make this into a pull request for the Final Project, please let me know but I just want to submit this for now letting you know I am finished and hopefully I can still get the on-time grade.

**Comment by hectorsector** [comment]
Thanks, I will grade it from there.

**Comment by hectorsector** [comment]
@bbutner1 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
