### ISSUE TITLE
ZPeterson2's Final Project Proposal

### ISSUE THREAD

**Issue by ZPeterson2** [cop1000/final-project#28]
**Please change the Title of this issue to include your username, something like: hectorsector's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Zaquonya Peterson

### Proposed Project Description
For my final project I will make a Christmas present idea generator. There will be about 10-15 questions. At the end you will receive the best Christmas idea based on your answers. I will also add Christmas music to play in the background. I might also add the best store to find your present.

### Connecting Concepts
This project will use JavaScript, HTML/CSS, and Bootstrap
### Timing
I will be finish with this project before the deadline.
12/6 create questions
12/7 work on quiz layout
12/8 add music and answers
12/9-12/12 finalize quiz

### Asking for...
Feedback on what types of questions or presents I should use. Anything that will make idea better.

**Comment by mirenagreen** [comment]
Hi @ZPeterson2  your project sounds interesting! I would add HTML/CSS and Bootstrap to your project to make your website look better :simple_smile:

**Comment by ZPeterson2** [comment]
Thanks @mirenagreen will do!

**Comment by hectorsector** [comment]
@ZPeterson2 I'd like to know a little more about how the questions will relate to presents. It seems like you've set a deadline of today for that yourself, so please post that in here and I will look it over and approve once you've got that.

**Comment by jriosrodriguez** [comment]
Looks like a fun idea. I might probably use it, haha picking gifts isn't that easy sometimes. Some ideas: you could also add some festive images (candy cane, Christmas tree, gifts, etc.) and narrow it down to a specific category (for her, him, old, young, etc.). Overall, excellent!

**Comment by ZPeterson2** [comment]
@hectorsector The questions will break the presents into catagories based on age, sex, interest and relationship. There will be a total of 25 questions and the answers will be gift ideas and the best places to shop, instead of specific presents.

**Comment by hectorsector** [comment]
@ZPeterson2 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
