### ISSUE TITLE
Nuridean's Final Project Proposal 

### ISSUE THREAD

**Issue by Nuridean** [cop1000/final-project#29]
### Name
Nuridean M. Mubarak 

### Proposed Project Description
I am planning to build a website for articles regarding e-sports news and other games with a navigation bar for each game and other user friendly features.

### Connecting Concepts
HTML, Bootstrap, 

### Timing
I would say it would take a week to finish or a little before the due date.

### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?

**Comment by kzeng16** [comment]
This sounds good. You could also add the top 5 teams in each game on the side.

**Comment by hectorsector** [comment]
@Nuridean JavaScript needs to be a part of your project as it was a big part of the course. Please think about making our idea a little more specific, and identifying what sort of JavaScript element you'd like to add.

**Comment by Nuridean** [comment]
@hectorsector is it ok if I did a generator that made something like a personality quiz for the game Warframe where the quiz asks you questions and it will tell you what warframe suit would suit you best.

Or something like a generator where the user has two drop down lists of elements from the game and combines them to create a damage type ex(fire + ice = blast OR toxic + fire = corrosive) I'm not sure how I would start this idea but both are ones that I would seem interested in

**Comment by hectorsector** [comment]
@Nuridean if you're not sure about how to start with that idea then take it simpler. How about your original idea for a sports news site, and you can use JavaScript for a collage or for embedding news from multiple sources or something like that? The reason I bring it up is that it doesn't sound like you want to do a generator so I'd like you to do something you enjoy.

**Comment by hectorsector** [comment]
@Nuridean Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
