### ISSUE TITLE
Rbowser5's Numeric Name-Value Generator Proposal

### ISSUE THREAD

**Issue by rbowser5** [cop1000/final-project#3]
### Name
Ryan Bowser

### Proposed Project Description
I want to build a program that converts each letter in one's name to a numeric value (A=1, B=2, etc.) and adds those numeric values to a number. I'd first work on the Javascript, using the lessons manipulating strings. Then I'd simply add the numbers together and have it output the final result. Then I'd build an HTML/CSS/jQuery-based website and see if I can make a full little program. The website would have an area to input the number, and then a dialogue box would open with the result. Hopefully I can make it look beautiful. 

### Connecting Concepts
String manipulation in Javascript, HTML, jQuery, CSS

### Timing
I'd like to get the Javascript part done by next Wednesday, the 6th. Then by December 10th, have the program ready.

### Asking for...
Positive vibes and some coding help for when I inevitably get stuck (haha).

**Comment by hectorsector** [comment]
This sounds fantastic just as you described it, 👍 from me. I think it definitely needs the web-page component. Check out some of the resources I left [on @JacobDanger's proposal](https://github.com/cop1000/final-project/issues/1#issuecomment-264350526) which may be helpful to you, too.

**Comment by GoogleFox** [comment]
Neat idea! Can't wait to see the value of my name 😃

**Comment by marxspawn** [comment]
@rbowser5 I agree with @GoogleFox, this is a really great way to show what we have learned this term. 
I too am going to incorporate my code into a web so that it can be a little easier to check out. Instead of downloading the code and running it through a browser anyway. 
Good Luck 👍

**Comment by bbutner1** [comment]
I got the idea of my project from this so thanks for some help. I am doing something similar to yours so let me know if you need any help with anything or if I could count on you to help me out if needed but I think this will be a neat tool once it's finalized.

**Comment by rbowser5** [comment]
@hectorsector @bbutner1 I'm running into some difficulty coding my javascript into a workable submit button/name text field.

Here's my code so far:

`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <h2 class="text-center"> Hello! Find out how much you are worth. </h2>
</head>
<script type="text/javascript">
  function str_split(string, split_length) {
  if (split_length == null) {
    split_length = 1;
  }
  if (string == null || split_length < 1) {
    return false;
  }
  string += '';
  var chunks = [],
    pos = 0,
    len = string.length;
  while (pos < len) {
    chunks.push(string.slice(pos, pos += split_length));
  }

  return chunks;
}


function count(string){
    var letters = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"];

    var splitted_string = str_split(string);

    var count = 0;
    for (i = 0; i < splitted_string.length; i++) {
        var letterPosition = letters.indexOf(splitted_string[i])+1;
        count = count + letterPosition;
    }
    return count;
}
document.getElementById("name").console.log(count("f"));
  </script>
<body>
 Name: <input type="text" Id="name"><br>
  <input type="submit" value="Submit" onclick=".console.log()">
</form>
</body>
</html>
`
I've been fiddling with it for a day or so now, and I haven't been able to find any help online past basic stuff. I want to get it to a point where I can press the submit button and a window pops up with the answer. (then I gotta make it look nice but that's the easy part.)

The Javascript works wonders, just not when I'm trying to combine it with the HTML. Any ideas?

**Comment by hectorsector** [comment]
@rbowser5 have you thought about using jQuery? Check out those lessons from FCC on that I think that'll be your easiest way out.

Regarding the code you've got so far, this line will cause errors (which you can see in your web browser developer tools):
```html
<input type="submit" value="Submit" onclick=".console.log">
```

**Comment by rbowser5** [comment]
https://jsbin.com/fumevadobe/edit?html,js,console,output

@hectorsector This is about as far as I've gone in about 6 hours of constant googling/trying stuff out. I can't seem to get anything related to JQuery to work. The code itself works fine, I just can't get the text box and submit button to actually input the information to the Javascript code.

**Comment by hectorsector** [comment]
@rbowser5 if you'd like to get together on chat we can try to sync up and maybe I can help you via a screen share or video chat. Ping me on gitter and we can come up with a time together. I am in California this week so I'm about 3 hours behind you.

**Comment by hectorsector** [comment]
@rbowser5 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
