### ISSUE TITLE
Snack-Pack's Final Project

### ISSUE THREAD

**Issue by Snack-Pack** [cop1000/final-project#30]
### Name
Pierre Dorlus

### Proposed Project Description
I plan to create a program that calculates calories burned after a run . Since i myself am on a diet i thought it would be a useful program to make. People would enter their weight and the distance they ran in miles to receive a result.  I plan to use JavaScript for my program and when it finished i will create a web page for it. I will most likly use a template for the web page

### Connecting Concepts
HTML/CSS,  JavaScript, Bootstrap, jQuery

### Timing
The project will be completed by the due date maybe sooner. the project layout should be finished by the 12th

### Asking for...
Any criticism or feedback on the site is valuable also if there are any bugs.

**Comment by hectorsector** [comment]
@Snack-Pack the idea seems pretty broad, might I suggest a small change? What if you program a simple nutrient calculator that will help people determine if a certain food is appropriate for a high-protein diet? Perhaps the calculator will look at the protein content and compare it to the calorie content (or something like that... you're the expert here 😉) and then tell someone either 👍 this food is acceptable in a high-protein diet or 👎 find a different food. You can always iterate on this idea later and add on the other elements you suggested, but I think that single calculator is sufficient and would hit all the requirements for the project. Let me know what you think!

**Comment by StephanNears** [comment]
This sounds like a great idea, I definitely need something like this in my life.

**Comment by Snack-Pack** [comment]
@hectorsector i was thinking about changing the project to something smaller. Instead of a site on the high protein diet i would instead make a program that can tell you the amount of calories you burn after a run. then i would make a web page for it.

**Comment by hectorsector** [comment]
Thanks for the update, @Snack-Pack. What will the user put in? The time they ran? And the program would then calculate calories based on time? Or will they input their stride length or anything like that?

**Comment by Snack-Pack** [comment]
@hectorsector I was thinking that they would enter their weights then the distance they ran in miles.

**Comment by hectorsector** [comment]
@Snack-Pack Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
