### ISSUE TITLE
Mirenagreen's Final Project Proposal

### ISSUE THREAD

**Issue by mirenagreen** [cop1000/final-project#31]
### Name
Milena de Oliveira

### Proposed Project Description
My final-project will be a website with reviews of the attractions of the Disney parks. Since I am always at Disney, when I have time, I thought it would be interesting to create a website that provide some reviews on the main attractions of the Disney parks and places to go. I plan on adding some pictures, ratings, reviews and the recommended ages. If the time allows me, I would like to create a generator where it will recommend the attractions you should go based on your age and on the days you plan to stay at Disney (it could help those visiting with limited time to spend on vacation). 

### Connecting Concepts
My website will use HTML and CSS for the overall design of the website, Bootstrap for response and mobile adaptation, and maybe JQuery. 

### Timing
I hope to have the skeleton of the pages completed by 12/8, the pages populated with valuable content by 12/11, and a generator for selecting an attraction or an itinerary by 12/14.

### Asking for...
Any kind of feedback will be welcome!

**Comment by mdean19** [comment]
That sounds awesome :) I'll definitely try out the generator

**Comment by hectorsector** [comment]
@mirenagreen I'd scale it back a bit and just do the suggestion generator by itself. That could have a small set of pre-populated recommendations (perhaps it can recommend one of the 4 Disney parks, or recommend a roller coaster, or something with a small data set like that). The generator would be accessed via  web page, but it doesn't need all that extra content for the purposes of this project. You can always add that in a later iteration. What do you think?

**Comment by mirenagreen** [comment]
@hectorsector I am going to work on rides generator mainly then. Thank you for the suggestion!

**Comment by hectorsector** [comment]
Great! Approved.

**Comment by hectorsector** [comment]
@mirenagreen Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
