### ISSUE TITLE
Ogivens Final Project proposal

### ISSUE THREAD

**Issue by orlandogivens** [cop1000/final-project#32]
Orlando Givens

For my final project I want to make a website celebrating how my favorite football team is doing this season. I'm an Atlanta Falcons fan. I would also like to capture some our top plays and moments that we have had this season. I would like to give you some background information about some of the stars of the team.  

During this project I will be using java, bootstrap

I think I will need a day or two to do the research. Then about 3 or 4 days to finish it. 

Any kind of feedback if possible.

**Comment by hectorsector** [comment]
@orlandogivens I would like for some of this information to be automated so you're not manually updating the team data. Could you see if there's a place you can grab that data from automatically?

**Comment by StephanNears** [comment]
That sounds like a great idea in theory, the automatic finding of information would make it great. Maybe you could use a sport network or something close?

**Comment by orlandogivens** [comment]
@hectorsector Yes I will.

**Comment by rthompson73** [comment]
@orlandogivens this sounds like a cool idea, I am interested in how you will get it working

**Comment by hectorsector** [comment]
@orlandogivens since the project is due tonight, please submit what you've got and I can grade it from there.

**Comment by hectorsector** [comment]
Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
