### ISSUE TITLE
Cjwilliams36's Final Project Proposal

### ISSUE THREAD

**Issue by Cjwilliams36** [cop1000/final-project#33]
### Name
Christian Williams

### Proposed Project Description
My project idea is to create a news website with articles on recent NSA, FBI, or government discoveries. It will also cover recent hacking attempts or data breaches and links to sites for people to learn how to secure themselves. There will be another section of the website where a user will be given his/her "hacker name" based on their date of birth. 

### Connecting Concepts
Javascript
HTML/CSS
Jquery

### Timing
I expect this project to be finished by the 12th. The website should be done by the 9th and the hacker name part should be done by the 12th giving me an extra day just for tidying up. 

### Asking for...
Is green text on black background still a cool thing to do? And if there are any articles you wish for me to put in the website feel free to let me know.

**Comment by hectorsector** [comment]
@Cjwilliams36 because we want to put our JS skills to good use, how about just the short hacker name app? I think this scope might be smaller, easier to tackle, and more applicable to our course.

**Comment by Cjwilliams36** [comment]
That sounds good to me. I'll get right on it.

**Comment by hectorsector** [comment]
👍

**Comment by hectorsector** [comment]
@Cjwilliams36 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
