### ISSUE TITLE
rthompson73 hectorsector

### ISSUE THREAD

**Issue by rthompson73** [cop1000/final-project#34]
### Name
Robert Thompson

### Proposed Project Description
For my project I want to create a website that helps with picking colors.  I want it to be directed specifically at people like graphic designers.  I will have a place to input the hexadecimal value for a color, and it will return with the opposite color.  
### Connecting Concepts
What lessons/topics will this project allow you to practice? A good final project will cover at least 2 big picture topics from class.
HTML/CSS
Javascript
### Timing
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates.
I will dedicate a portion of time each day to work on this project in order to finish by next week.  
### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?
I am interested in suggestions for what might add some more functionality.

**Comment by jnorris18** [comment]
This is a really creative idea that I think could be very useful. I think you can definitely finish this in time for the final, and should get a great grade if you do it right.

**Comment by hectorsector** [comment]
Sounds like a neat idea, @rthompson73. How will you determine the opposite of a color?

**Comment by rthompson73** [comment]
@hectorsector I would determine the opposite of a color by replacing each hexadecimal value with its opposite, 0 becomes F, 1 becomes E, and so on.  A full value would be something like, 000000 becomes FFFFFF, or 012345 becomes FEDCBA.

**Comment by jriosrodriguez** [comment]
I like it. Opposite colors, I think, tend to compliment each other. This will certainly help any designer and cut down some work time.

**Comment by hectorsector** [comment]
Got it -- great idea.

**Comment by hectorsector** [comment]
@rthompson73 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
