### ISSUE TITLE
Mikedaris94 Proposed Project

### ISSUE THREAD

**Issue by Mikedaris94** [cop1000/final-project#35]
Mike Daris

Proposed Project Description

I am going to create a website based on the Kingdom Hearts game series. The newest Game will be releasing on January 12th, 2017 and I am super excited about it. I will be creating a page showing a timeline through the series and describing all the major characters with a brief bio of them.

Connecting Concepts
I will be trying to implement the use of  HTML, CSS, and Bootstrap.

Timing
First I will be gathering unknown information
Then I will be gathering pictures 
Next I will be trying to insert our connecting concepts 
Last I will be reviewing all work so it is correct and ready to submit by the 14th

Asking for...
Any feedback or suggestions anyone may have to improve the quality of my work.

Thank you,

**Comment by jnorris18** [comment]
Awesome subject to base your website off of. I am also working on a website design for my final. I think we will both have enough time to finish this project completely as you seem to know a lot about Kingdom Hearts just as I do with my subject.

**Comment by hectorsector** [comment]
@Mikedaris94 how exactly will your web site use JavaScript?

**Comment by Mikedaris94** [comment]
@hectorsector sorry professor i won't be using JavaScript in the project i was going to try but i don't see a good way to fit it in

**Comment by hectorsector** [comment]
@Mikedaris94 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
