### ISSUE TITLE
Samuel's Final Project Proposal

### ISSUE THREAD

**Issue by SPierre30** [cop1000/final-project#37]
Name
Samuel Pierre

Proposed Project Description
My idea for a proposed project is to create either a mind reading app or a matching game. Honestly, with such a late time to start I don't think I'll finish it in time but I do want to try to make one. I would like this game to use images from google and be based off of anime photos from different books.

Connecting Concepts
What lessons/topics will this project allow you to practice? A good final project will cover at least 2 big picture topics from class.
I'd like to use Html and JavaScript
### Timing
I'd like to give myself a day for the images and several days to come up with a proper code. I have an idea of one to start off from which I'll link it when I've begun.

### Asking for...
First off, I'd like to know if this would be a good idea and if anything, is it possible for the photos to be properly mixed o_O, not sure if that makes much sense.

**Comment by jnorris18** [comment]
This idea is awesome. I think it will be very challenging to finish one of these in time for the final, but if you can do it right I am certain you can get an A. Good luck as I had some trouble with the app coding.

**Comment by hectorsector** [comment]
@SPierre30 since you're crunched for time please think about how you could modify your project so you can finish it in time. Sacrifice the scope of the project, not its quality.

**Comment by SPierre30** [comment]
Since I'm a big fan of One piece, I think I'll just cut down on the books and focus on specific group of characters in the series. Or maybe even just the crew alone. I''ll focus on a matching game since the mind reading one would definitely take much longer. I'd also like to try and implement 2-3 groups so it wouldn't be the same group of people the entire time.

**Comment by hectorsector** [comment]
Alright, @SPierre30 could you describe the matching game in a little more detail? I'm not sure how it's going to work.

**Comment by Mikedaris94** [comment]
this seems like a good idea I hope you finish in time.

**Comment by SPierre30** [comment]
Thanks xD lol. I'm actually almost done but I'm having trouble doing a pull request

**Comment by SPierre30** [comment]
Um and @hectorsector, it's supposed to be a matching game involving one piece characters. So far the only issue I'm having is the images aren't getting attached to my array.

**Comment by hectorsector** [comment]
Thanks for the update, @SPierre30. Since the project is due tonight please turn in what you've got and I'll take it from there.

**Comment by hectorsector** [comment]
@SPierre30 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
