### ISSUE TITLE
jnorris18 Final Project

### ISSUE THREAD

**Issue by jnorris18** [cop1000/final-project#38]
John Norris

Proposed Project Description:
I will create a fan page website to give information about the Los Angeles Laker's all time greatest players. On this site I will provide info on records they hold, stats, pictures, and other important facts. I am not sure yet how many players I will include, but in my opinion there is around 6-7 hall of fame players from the Lakers worth providing information about. I am a huge fan of the team so this will all be accurate information and stats.

Connecting Concepts:
This project will work off of the javascript coding lessons and one of our other projects which tasked us to design a website. I feel like I got the hang of these lessons the best and would like to use my skills I have learned to get an A on the final.

Timing:
I should be able to finish this project fairly quickly. Like I said I grasped these lessons the best and I also know ample amount of information about the topic I am choosing to design the website about.

Asking for:
Just making sure that the coding is correct and in the correct placing for the website to look the best it can at my level of programming.

**Comment by hectorsector** [comment]
@jnorris18 how exactly will your project utilize JavaScript?

**Comment by jnorris18** [comment]
My project will utilize JS in the page navigation(buttons) and  HTML5 and CSS adding images and page layout.

**Comment by jnorris18** [comment]
I have emailed you a few times in regards to my last project. I have not got a response yet and would just like to let you know I have completed it and am hoping you can accept it as late work. Below is the list of URLs as I was not able to the challenges to github, I believe this is because the algorithm challenges branch is closed. Please email me back when you can. Thanks for your help.
challenge 1(comments): https://github.com/cop1000/algorithm-challenges/commit/badf41706da4414aa66b6b3a394b3bd17e7b69fd
challenge 15(solving): https://github.com/cop1000/algorithm-challenges/commit/dbf6ec91da79e426219afd7c2c224db72786319e
challenge 16(testing): https://github.com/cop1000/algorithm-challenges/commit/04414efe320b9df14bb0eb68a62f906f9b15d47d

**Comment by hectorsector** [comment]
@jnorris18 I see you emailed me on Saturday -- please note that I do not check email on the weekends and my response time will be at least 24 hours during regular business days. Thanks for sending me this, but please keep all other communication regarding your grade to a private chat or email. I will respond there.

**Comment by hectorsector** [comment]
@jnorris18 I'd think a little deeper about the use of JavaScript. How will the buttons themselves utilize JavaScript?

**Comment by jnorris18** [comment]
The buttons will utilize javascript by providing external links in which the viewer can click and be navigated to a new page.

**Comment by hectorsector** [comment]
@jnorris18 thanks, but that doesn't require JavaScript, just plain HTML. Since the project is due today, please turn in what you've worked on and I can grade it from there.

**Comment by jjyates4** [comment]
Lakers are my favorite team! I am looking forward to see how you will do this. Kobe definitely should be in there haha.

**Comment by hectorsector** [comment]
@jnorris18 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
