### ISSUE TITLE
AntoineDS Final Project

### ISSUE THREAD

**Issue by AntoineDS** [cop1000/final-project#4]
### Name
What's your real name? Enter your first and last name in place of this text, please.

Antoine Stimphil

### Proposed Project Description
My proposed Final Project will be a website describing the importance of programming. Within my website I will describe a few major languages and what a programmers are able to produce with these languages. The website will be a bootstrap website using HTML5, CSS3, and Javascript to fully express the information I will be presenting. I have chosen bootstrap because it is a familiar language that has great stability and provides a great user experience. During my final project this will be my first attempt in using Javascript in a website. I will be using Javascript to create a contact form that will be used if future employers are interested in hiring me they will be able to contact me through my website. 

### Connecting Concepts
What lessons/topics will this project allow you to practice? A good final project will cover at least 2 big picture topics from class.

This topic will allow me to cover CSS, and Javascript. During my time within my course we have covered CSS and Javascript so it is only right to have these included within my project.

### Timing
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates.

The Final project will take me until December 14th to complete due to the extent of how much information I will be placing within the website. On the 7th I will have a full layout of the project with the information that will be placed on the website. From the 7th to 14th I will be focusing on the design of the website which include adding touch ups to the CSS and javascipt portion of my final project.

### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?

The best possible feedback my professors and classmates could give me is if they encountered any bugs and what I could have done to make their interaction with the website more friendlier for them. Which include full detail descriptions and not things like "you should have better color", and more like "The color on the drop down menu blended into the page background making viability hard when choosing different pages.". This feedback will allow me to be more successful and would be deeply appreciated.

**Comment by hectorsector** [comment]
> With Javascript it will provide a interactive interaction for my users.

@AntoineDS can you elaborate a bit on the JS interaction you're thinking of providing?

**Comment by AntoineDS** [comment]
I'm aiming to use a JavaScript Modal that will allow page visitors an option to leave feedback. I do not fully understand how to create a feedback form using JS but I do know that it is possible.

**Comment by AntoineDS** [comment]
Proposal has been updated!

**Comment by hectorsector** [comment]
Sounds good, @AntoineDS. Carry on!

**Comment by hectorsector** [comment]
@AntoineDS Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
