### ISSUE TITLE
jjyates4's Final Project Proposal

### ISSUE THREAD

**Issue by jjyates4** [cop1000/final-project#42]
**Please change the Title of this issue to include your username, something like: hectorsector's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Jordan Yates

### Proposed Project Description
Give a detailed description of what you'd like to do for your final project (5+ sentences). Feel free to replace this text with your description. 
For my final project, I would like to create a blog site that is exclusively for sports. I've always loved watching and playing sports. I feel that it could be a good way to compete with ESPN sites. This will be a way for sports enthusiasts to discuss sports topics. This will also be a way for sports enthusiasts to stay updated with the latest sports information.

### Connecting Concepts
JavaScript, HTML & CSS.

### Timing
I would like to complete the actual interface with the color and designs of it by the 12/12 and the functions of the site (as in navigating the site) by at least 12/13.

### Asking for...
I would like feedback on the structure of the website

**Comment by hectorsector** [comment]
@jjyates4 how exactly will your site use JavaScript? Could you please clarify? Thank you.

**Comment by jriosrodriguez** [comment]
This sounds like an excellent idea! Some questions to help you out in the process: Are you planning on focusing on a specific sport or different sports with different sections for each? Compared to an ESPN, how is your website going to be different? How do you plan on organizing the information?

**Comment by jjyates4** [comment]
@hectorsector  I will use JavaScript to program the behavior of the webpages that I will use.
@jriosrodriguez Thanks! I will use different sports with different sections. As for the second question, I will try to place the sports navigation tool as vertical on the left side of the page versus ESPN's  horizontal navigation tool at the top.

**Comment by rthompson73** [comment]
@jjyates4 this sounds like a vary interesting idea, can't wait to see it finalized

**Comment by jmasterson5** [comment]
sound like a great Idea and maybe you can even have a feature where people can favorite there favorite sport players

**Comment by hectorsector** [comment]
@jjyates4 since the project is due tonight, please submit what you've got and I can grade it from there.

**Comment by hectorsector** [comment]
@jjyates4 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
