### ISSUE TITLE
aalevane's Final Project Proposal

### ISSUE THREAD

**Issue by aalevane** [cop1000/final-project#5]
### Proposed Project Description
I would like to design and code the front-end of a photography portfolio. I would like to eventually work as a front-end web developer and think this would be a great opportunity to get real-life practice. I want the website to have a simple yet modern design, multiple pages, a gallery/slideshow and a contact form. I also want it to be mobile-responsive and have some interactive elements. I'm debating whether I should use Bootstrap to make it responsive or try to make it responsive myself.

### Connecting Concepts
I will be using HTML & CSS for the structure and design of the website, jQuery for interactivity and the gallery/slideshow, and possibly Bootstrap to make it responsive.

### Timing
Since I've never done a full project like this I'm not sure how accurate my estimates are but hopefully I won't run into many roadblocks. I'm taking into consideration how well-versed I feel in each skill as well as whether or not I have work that day when allotting time to each stage:
1. Research - Browse the web for design inspiration as well as how different gallery/slideshows function (~30min-1hr) **12/7**
2. Design - Experiment with different portfolio designs and decide which one I'll be coding (~1-2hrs) **12/7-12/8**
3. Code HTML & CSS - Start with the structure and design of the page, possibly use Bootstrap for responsiveness (~2-3hrs) **12/8-12/9**
4. Add jQuery - Add the image gallery/slideshow as well as some interactivity where appropriate (I'm thinking links, text, menu) without overdoing it and compromising the design (~2hr) **12/9 & 12/11**
6. Troubleshoot / fix any bugs - Making sure I leave some extra time in my schedule in case anything isn't functioning properly and I need some extra time to research/ask for help/fix any bugs (~1-2hrs) **12/11-12/12**

### Asking for...

Should I use Bootstrap to make the website responsive or should I try to do it myself with HTML & CSS? I've read online that it's better to learn to do it yourself from scratch before using a tool like Bootstrap since it helps you understand how it all works better but I'm not sure if I'm just giving myself more work or if it's just better to start practicing using a popular tool like Bootstrap.

**Comment by hectorsector** [comment]
> Should I use Bootstrap to make the website responsive or should I try to do it myself with HTML & CSS?

Based on your long-term goals, it sounds like you might benefit from doing this from the ground-up, but I'm concerned that it may not give you enough time to add some the JS elements that I'm interested in seeing in your project (because at the end of the day this is a programming class and I want to ensure you've grasped programming concepts -- HTML and CSS are not quite programming languages. So, my suggestion is to not reinvent the wheel this time around and use Bootstrap.

> jQuery for interactivity and the gallery/slideshow

Could you do a little research on what sort JS tool you can use for a slideshow and/or gallery? Once we've got that pinned down I'll be comfortable 👍 this.

**Comment by aalevane** [comment]
What if I just use plain JS for the image gallery/slideshow?

**Comment by hectorsector** [comment]
That's alright with me!

**Comment by hectorsector** [comment]
@aalevane 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
