### ISSUE TITLE
cistivela1217's Final Project Proposal

### ISSUE THREAD

**Issue by cristivela1217** [cop1000/final-project#50]
**Please change the Title of this issue to include your username, something like: hectorsector's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Cristina Velasquez

### Proposed Project Description
In my project I am planning on creating a website. This website will be based on the top colleges of my choice since I am currently still a high school student. The website will include the location and details about my top colleges. It will also include images of the campus. There will also be link leading to the website of the website of choice. And there will be buttons that lead to different parts of the website.

### Connecting Concepts
The website will include HTML5 and CSS as well as Bootstrap, jQuery.

### Timing
This website will take me approximately a week to complete

### Asking for...
Feedback that I would appreciate are new aspects that weren't previously learned to add to my website.

***I was previously partnered with Joel Rios but there was an issue so we each decided to do our own project separately****

**Comment by hectorsector** [comment]
@cristivela1217 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
