### ISSUE TITLE
radicalpharaoh's Final Project Proposal

### ISSUE THREAD

**Issue by radicalpharaoh** [cop1000/final-project#6]
### Name
Jose Pena

### Proposed Project Description
For a final project, I would like to revisit the the github.io project we did earlier in the semester. With more knowledge on how to operate html and coding, I want to create an informational website on the recently released Pokemon Sun and Moon. At first thought, Pokemon can be thought of as a relic in the past for everyone's childhood. That is true but that shouldn't mean you should leave that treasure to collect dust. With Pokemon Sun and Moon, there were three phases of the game that I want to cover and with a website, I can categorize, organize and inform others (mostly me and my group of friends) on how to approach the game. Basically, for this project I want to create a website that contains information necessary to beat the endgame content of Pokemon Sun and Moon, incorporating multiple graphs, guides and personal discussions, links to video tutorials, GIFs of mini-tutorials to help better illustrate what to do for the endgame content and how to approach it. Pokemon Sun and Moon may seem like a simplistic game to some, it maybe for anyone reading this, but deep below the childhood memories and the "cutetsy" design of the creatures that dwell in this game, there stands a monolith of mathematical anomalies and tedious actions that must be covered to become the "very beat" (*Queue the Pokemon theme song*).

### Connecting Concepts
The usage of **HTML** , **JavaScript** and **CSS** for the design of the website is necessary for this project. Also, **jQuery** for the ability to interact and choice what information to display. And of course, adding **Bootstrap** to the project.

### Timing
**Research / Crafting Design Ideas** - I will need to research the endgame content of Pokemon Sun and Moon. Go over the Effort Values and Individual Values (Values assigned to each Pokemon to increase their performance) necessary to tackle endgame.  The amplification provided to the power by natures, traits or attitude held by Pokemon that increases their values  The processes of breeding the correct Pokemon and allowing for the values I mentioned earlier to transfer to each offspring via breeding. Alongside the research, I want to also think of how to lay out the website so it can provide the information smoothly as possible and finalize the concept of it. **12/5**

**Coding** - The bulk of the entire work. Incorporating my knowledge of HTML, CSS, jQuery and Bootstrap to make the website as fluid as possible. **12/5 - 12/10**

**Fix** - Any issues, new ideas or problems that I want to cover will be across these two day periods. **12/11 - 12/12**

### Asking for...
Any criticism or feedback on this idea would be **heavily appreciated**. I want to know how I can better approach my goal and have the right information necessary to achieve it.

**EDIT**
Included JavaScript into the Connecting Concepts section

**Comment by aalevane** [comment]
I love this idea! Really looking forward to the pokemon projects I've seen on here. However I have a feeling professor is going to require more JavaScript in your project. I saw him recommend to someone else a sort-of random quote generator that will generate random gifs from the game. I think that would be cool. Or maybe a random quote generator somewhere on the page that generates random tips and tricks for the game.

**Comment by KaidyCEThomas** [comment]
These Pokemon projects are really intriguing and I'm excited to see the end result. I agree with @aalevane regarding the professor's comment in wanting to see your Java skill through this project. Great timeline too!!

**Comment by mariadodoll** [comment]
I really like your idea. I cant wait to see your ideas implemented and see the final result.

**Comment by radicalpharaoh** [comment]
Okay! Thanks for the feedback! Means a lot. I'll incorporate more JavaScript like the professor mentioned in the earlier issues, using either GIFs of gameplay how to approach the values of the Pokemon or the statistic graph the game employs. Will try to think of more ideas. Thank again.

**Comment by hectorsector** [comment]
@radicalpharaoh good proposal. I suggest we scale back the content of the web site quite a bit. Can you create more of a microsite that can contain a very specific piece of content. If you have extra time to add some more, great! But great projects are created one little iteration at a time. So: if you had to create only a three-page site, what content would you include?

The second question I'd ask you to consider, is how exactly you plan to use jQuery or JavaScript. If we can identify one use in particular, I'm happy to approve this. Some examples might be: use jQuery to create animations for the menu, include a slideshow for images powered by JavaScript, include a different random motivational Pokemon picture every time someone visits the site (also done through JS).

**Comment by radicalpharaoh** [comment]
If I were to create only three pages, I would probably just include the intro page, with like a summary of what Pokemon is and what initiatives a player can be to be the very best with a slideshow (**JavaScript**) of the Pokemon a player can get to become the "best". And then it will split into two other pages. Second page: A summary of what Natures (hidden stat bonuses) are in the World of Pokemon and a breakdown of what payers can apply them to. Third page: a summary of what EV and IV points (bare-bones explanation) are with inclusion of a graph to better paint what they are with probably a picture or two of Pokemon that has synergies with the topic. Thank you for the feedback, Professor. It is always appreciated. Hopefully I made my proposal more thoroughly explained and the changes requested are met.

**Comment by hectorsector** [comment]
Sounds good. Carry on!

**Comment by jjyates4** [comment]
I love this idea! Coming from a huge Pokemon fan, can't wait to see it.

**Comment by hectorsector** [comment]
@radicalpharaoh Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
