### ISSUE TITLE
lminks' Final Project Proposal

### ISSUE THREAD

**Issue by lminks** [cop1000/final-project#7]
### Name
Luke Minks

### Proposed Project Description
I am strongly considering a script that analyzes the character composition of a string. Such a program would count the number of each letter in a string and save them to individual totals, then perhaps output both the total number of appearances and what percentage of the string each letter makes up. I could also include comparisons to how much more or less frequently each character occurred relative to the average frequency in the English language, expressed as a percentage; I might limit this to only return characters that were significant outliers to prevent the amount of information displayed from becoming overwhelming. I plan on working alone for this project.

### Connecting Concepts
This program would be written using Javascript and would pull a lot from string manipulation and logic operators; it would also rely heavily on the use of variables and mathematical operations.

### Timing
I do not anticipate the program being excessively complex or lengthy, so I would probably be able to complete the bulk of the code within a day. Most of the time required will be spent revisiting string manipulation and gathering information to use for additional functionality such as relative frequency compared to the English language. I would probably spend most of this week doing some research and information collection and then spend the weekend coding and refining the program; any time during finals week that I have available would be spent doing mild tweaks and making sure the rest of the accompanying material is complete.

### Asking for...
I'm mostly just looking for confirmation that this is a reasonably-sized project to pursue. I don't want to take the easy way out and pick something that would take 5 minutes to code, but I also don't want to pick something too complicated since I'm still new to this and have other classes to consider. If this program seems too simplistic, let me know how I can add to it.

**Comment by GoogleFox** [comment]
I like this idea! Hope it works out for you! 👍

**Comment by StephanNears** [comment]
The idea doesn't seem to simple to me. If you want to make it more interactive you can have some sort of sounds and fanfare to go along with the program. It would be a simple way to give it more "substance" if that's what you're looking for.

**Comment by vcomney** [comment]
I don't think it sounds like a simple idea either. I think there is nothing wrong with not over thinking it too much. I say stick to the core concept and don't worry about adding too much. Unless, you feel that there is a direct correlation to the function of the application. Garnish should always have function, if that makes sense.

**Comment by hectorsector** [comment]
Great idea, @lminks! I'll echo what others have said -- I don't think this is too simple. It might also take you longer than a day to code, so please plan accordingly.

One thing you might think about is where you'll pull the data about frequency of letters in the English language. Is there an API you can use to help you with that? Or is that basic stuff you can hardcode in?

**Comment by hectorsector** [comment]
@lminks 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
