### ISSUE TITLE
marxspawn's final project proposal

### ISSUE THREAD

**Issue by marxspawn** [cop1000/final-project#8]
### Raymond Anderson
My Github handle is marxspawn

### Java Web Coding
- My design is going to show what type of basic coding I have learned this term. My plan is to build a web page that will have various small codes written throughout. Most of the codes will be in java along with some bootstrapping, as well as the html and css coding that would normally be present in any basic web page. The page itself (although generated through GitHub pages) will be reworked by me to fit my needs along the lines of the visual aspect of the whole design.

### Continuing my programming knowledge
- Basically I will be continuing to practice small coding and implementation into designs. Also this project will help me out with github’s branch, sync, merge, pull concept, which every time I think I have it down the desktop app throw’s me through another loop :smiley_face: I have learned quite a bit through this course and as unsure as i was about taking this class as an online course, I am quite pleased with my choice. Thank you @hectorsector I enjoyed it

### Timing
- I have a basic start on my web page with only a couple days of work into it (I would say around 5-6 hrs total thus far). To complete my design with full implementation should take me around a weeks time :pray:

### Ideas and Suggestions
- I always appreciate any type of critiquing on my work no matter how big or small it may seem. Please feel free to leave any feedback, even if it may come across as being negative. I like to take all suggestions and use them to build from

- Please visit my project [README.md](https://github.com/marxspawn/webBasedJavaDemo/blob/master/README.md) 

# Good luck to everyone :metal: :neckbeard:

**Comment by JBrady22** [comment]
Overall i would say this is an ingenious idea for the project. I did something like this for a essay i wrote in middle school where my essay was about someone else going through the process of writing an essay. Got and A by the way. But yeah i think this will not be too difficult. i just hope you get approved because you have already put time into it.

**Comment by KaidyCEThomas** [comment]
What a thoughtful idea for your project! As a visual learner I'm interested to see how you implement your design and visual graphics.

**Comment by mariadodoll** [comment]
Great Idea. Your project does not seem like too much work to be done in 1 week its definitely achievable.  Your project will utilize topics learned throughout the semester.

**Comment by hectorsector** [comment]
@marxspawn good start, but I'd like to know more specifics about what you'll be adding to your web page. Are you creating a portfolio of your work? Or are you creating multiple code snippet examples?

**Comment by marxspawn** [comment]
@hectorsector Basically the page will be a few interactive snippets that demonstrate how java, jquery, or bootstrapping can be implemented into a web page. Along with a separate page that will incorporate CodeMirror so you can practice with your own codes.

**Comment by marxspawn** [comment]
wrong button ☝️ 😬

**Comment by hectorsector** [comment]
Alright that sounds good, go ahead and implement @marxspawn!

**Comment by hectorsector** [comment]
@marxspawn 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
