### ISSUE TITLE
emerced2's Final Project Proposal

### ISSUE THREAD

**Issue by emerced2** [cop1000/final-project#81]
**Name**
Edwin Merced

**Proposed Project Description**
For the final project, I would like to keep it somewhat simple in theory. I'm going to work on a basic html page, where the user can input text (english alphanumeric) and get a return of that text translated into binary. I know, I'm geeking out on a pointless topic but I wanted to focus on JS and problem solving on that end opposed to focusing on the site itself. I would like to keep the JS simple as well, using topics learned through the semester, but might need help from others with more JS and problem solving experience. The end result will not be "flashy" cosmetically, but what it lacks visually will be made up for in the JS coding.

**Connecting Concepts**
HTML and CSS
Basic JavaScript
Object oriented and functional programming
for loops, etc.

**Timing**
I believe this project will take no longer than a week to be completely functional. I will possibly take a few days working on cosmetics, possibly. The majority of the time will be figuring out how to code the JS portion of the project. For the JS coding, I'm giving myself five days to figure it out, any longer and I'll be desperate for your guys help! for the HTML I'm only spending any additional time left over. Again, I'm only incorporating HTML because I'm starting to understand the importance, I will not be focusing on it very much.

**Asking for**
ANY advice or help please! Any and all feedback for any portion of the project will be accepted, taken into consideration, and appreciated.

**Comment by hectorsector** [comment]
@emerced2 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
