### ISSUE TITLE
Scoping Section

### ISSUE THREAD

**Issue by aarvizu** [cop1000/final-project#82]
**Please change the Title of this issue to include your username, something like: hectorsector's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Alexis Arvizu
What's your real name? Enter your first and last name in place of this text, please.

### Redesigning the Original Website assignment
Give a detailed description of what you'd like to do for your final project (5+ sentences). Feel free to replace this text with your description.

### HTML, Bootstrap, and JQuery
What lessons/topics will this project allow you to practice? A good final project will cover at least 2 big picture topics from class.

### one week
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates.

### Feedback can include anything from how crazy this idea for a project is or how i can approach this idea when initially coding it.
What kind of feedback can your classmates and professor provide to help you be successful?

**Comment by hectorsector** [comment]
@aarvizu Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
