### ISSUE TITLE
StephanNears's FInal Project Proposal

### ISSUE THREAD

**Issue by StephanNears** [cop1000/final-project#9]
### Name
Stephan Nears

### Proposed Project Description
I would like to make a small random generator that makes a match using a small quiz and your name to choose the right Pokemon for you. Been playing it for 10+ years and I think I can make a responsive enough quiz game for it. I would expect to use Java script to link up certain responses with certain sprites and information. I would use the remaining Html/CSS and such to make the rest of the site look nice.

### Connecting Concepts
JavaScript, Html,CSS...

### Timing
Javascript done by the 8th and the rest of the site would be done by the 12th, if not earlier.

### Asking for...
Tell me if I'm aiming to high, or If There's not enough there. I'm always ready for some sort of feedback.

**Comment by aalevane** [comment]
I don't think you're aiming too high, it seems like the perfect project. Plus the Pokemon theme gives it extra points in my book 👌

**Comment by JBrady22** [comment]
Stephan i believe we had very similar ideas for this project and i look forward to seeing your end result. Overall i think this cane be done in a week and will not be too difficult or too easy to complete but just right.

**Comment by Jordan-Hosein** [comment]
Sounds fun, I'm interested in seeing what Pokemon I get! 
I don't think you're aiming too high at all either
I've always liked Eevee, but Rockruff in the Sun and Moon might be replacing it.

**Comment by mariadodoll** [comment]
This sounds like a great concept. You are definitely not aiming to high. I think your timing is achievable.

**Comment by MCastro46** [comment]
I need you to rig it, so when a friend of mine does it, he'll always get Jynx. Nah im messing with you in super excited to see where this leads! also @Jordan-Hosein  Eevee For life. for get Rockruff D:< 
although, Lucario > all :D   
![image](https://cloud.githubusercontent.com/assets/21311831/20898241/9d95fb62-baf3-11e6-960e-8758c899a2d4.png)

**Comment by vcomney** [comment]
I think this is a rad and original idea. I'd be curious to see how it matched me up with the right poke'mon. It's a great all ages friendly project. Pretty cool.

**Comment by hectorsector** [comment]
@StephanNears the idea seems great.

I would focus on creating the mapping of how names will relate to the quiz they get, and actually create the quiz content as well before you start coding.

**Comment by Jomarm92x** [comment]
I love pokemon so I'm excited to see how this will work, just tell me how I can get Charizard haha.

**Comment by rbowser5** [comment]
That sounds like an awesome idea! I better get Charmander lol. Making it mobile-friendly could make it even cooler!

**Comment by StephanNears** [comment]
Now that I think of it I might change out using the name as a bases for the choice. The name will just be part of the Response. "Blank is this Pokemon!" That's how I feel it should be.

**Comment by hectorsector** [comment]
@StephanNears Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.
